remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

navigation: true

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
