remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

include: ["_pages"]

minimal_mistakes_skin: default

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      sidebar:
        nav: "" 
      author_profile: false
