remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

include: ["_pages"]

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
