remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

include: ["_pages"]

minimal_mistakes_skin: default

sidebar:
  - title: "Title"
    image: http://placehold.it/350x250
    image_alt: "image"
    text: "Some text here."
  - title: "Another Title"
    text: "More text here."

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      sidebar:
        nav: "" 
      author_profile: false
